package com.flightapi.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents a flight booking entity in the system.
 * Stores information about a booking, including the user who made it, the flight details,
 * booking reference, status, time, total price, and associated passengers.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "BOOKING")
public class Booking {

    /**
     * The unique identifier for the booking.
     * Generated automatically by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "booking_id")
    private Long bookingId;

    /**
     * The user who made this booking.
     * This is a many-to-one relationship with the {@link User} entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The flight associated with this booking.
     * This is a many-to-one relationship with the {@link Flight} entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "flight_id", nullable = false)
    private Flight flight;

    /**
     * A unique reference code for this booking.
     * This field is unique and cannot be null.
     */
    @Column(unique = true, nullable = false, length = 20)
    private String reference;

    /**
     * The current status of the booking (e.g., "CONFIRMED", "CANCELLED").
     * This field cannot be null.
     */
    @Column(nullable = false, length = 20)
    private String status;

    /**
     * The timestamp when the booking was created.
     * This is automatically generated by the database and cannot be updated.
     */
    @CreationTimestamp
    @Column(name = "booking_time", nullable = false, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private LocalDateTime bookingTime;

    /**
     * The total price of the booking.
     * This field cannot be null.
     */
    @Column(name = "total_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalPrice;

    /**
     * The list of passengers included in this booking.
     * This is a one-to-many relationship with the {@link Passenger} entity.
     * Changes to this booking (e.g., deletion) will cascade to the associated passengers.
     */
    @OneToMany(mappedBy = "booking", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Passenger> passengers;
}
